server:
  port: 9000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.160.129:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-order
  rabbitmq:
    virtual-host: /
    host: 192.168.160.129
    port: 5672

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto